// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckController from "./check_controller"
application.register("check", CheckController)

import SentenceLoadingController from "./sentence_loading_controller"
application.register("sentence-loading", SentenceLoadingController)
